// <auto-generated />
using Login.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Login.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241122050342_db")]
    partial class db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Login.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailId = "johndoe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "password123",
                            UserName = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            EmailId = "janedoe@example.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Password = "password456",
                            UserName = "janedoe"
                        },
                        new
                        {
                            Id = 3,
                            EmailId = "michael.smith@example.com",
                            FirstName = "Michael",
                            LastName = "Smith",
                            Password = "michael123",
                            UserName = "michaelsmith"
                        },
                        new
                        {
                            Id = 4,
                            EmailId = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            Password = "emily2024",
                            UserName = "emilyj"
                        },
                        new
                        {
                            Id = 5,
                            EmailId = "william.brown@example.com",
                            FirstName = "William",
                            LastName = "Brown",
                            Password = "william@321",
                            UserName = "william_b"
                        },
                        new
                        {
                            Id = 6,
                            EmailId = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            LastName = "Taylor",
                            Password = "olivia@123",
                            UserName = "olivia_t"
                        },
                        new
                        {
                            Id = 7,
                            EmailId = "james.martinez@example.com",
                            FirstName = "James",
                            LastName = "Martinez",
                            Password = "james456",
                            UserName = "james_m"
                        },
                        new
                        {
                            Id = 8,
                            EmailId = "sophia.davis@example.com",
                            FirstName = "Sophia",
                            LastName = "Davis",
                            Password = "sophia789",
                            UserName = "sophia.d"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
